question_data = [
    {"category": "Entertainment: Video Games",
     "type": "boolean",
     "difficulty": "medium",
     "question": "Amazon acquired Twitch in August 2014 for $970 million dollars.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
     "question": "A person can get sunburned on a cloudy day.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "The first computer bug was formed by faulty wires.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "Animals", "type": "boolean", "difficulty": "medium",
                                      "question": "The Ceratosaurus, a dinosaur known for having a horn on the top of "
                                                  "its nose, is also known to be a decendent of the Tyrannosaurus Rex.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Celebrities", "type": "boolean", "difficulty": "medium",
     "question": "Michael Jackson had a pet python named &lsquoCrusher&rsquo.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "Arcade Fires The Suburbs won the Album of the Year award in the 2011 Grammys.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "Coca-Colas original colour was green.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                      "question": "The planet Mars has two moons orbiting it.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "medium",
     "question": "In the game Racko you may pick up ANY card from the discard pile.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "The first Maxis game to feature the fictional language Simlish was The Sims (2000).",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
     "question": "A defibrillator is used to start up a heartbeat once a heart has stopped beating.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "The country song  &ldquoA Boy Named Sue&rdquo was written by Shel Silverstein.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
     "question": "The Chevrolet Corvette has always been made exclusively with V8 engines only.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "Windows NT is a monolithic kernel.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The average woman is 5 inches \/ 13 centimeters shorter than the average man.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The term Spam came before the food product Spam.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "In Half-Life 2, if you play the zombies speech in reverse, they actually speak coherent English.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "Kissing someone for one minute burns about 2 calories.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                       "question": "There exists an island named Java.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
     "question": "The television show Doctor Who first aired in 1963.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
                                       "question": "When BMW was established in 1916, it was producing automobiles.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "The Snipers SMG in Team Fortress 2, was originally intended to be the Scouts primary weapon.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Gadgets", "type": "boolean", "difficulty": "medium",
     "question": "The Western Electric Model 500 telephone uses tone dialing to dial phone numbers.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "The first dual-core CPU was the Intel Pentium D.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                      "question": "Fast food restaurant chains Carls Jr. and Hardees are owned by the same company.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "In Riot Games League of Legends the name of Halloween event is called The Reckoning.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "In the video game Transistor, Red is the name of the main character.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
     "question": "A Millinillion is a real number.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
     "question": "Klingons once had a period of Democracy in their history, they referred to it as the Dark Times.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "The ADAM collecters in the Bioshock series are known as Little Sisters.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "In Starbound, the track played by the Decorated Music Box is named Atlas.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "In Call Of Duty: World At War, the first appearance of the PPSH-41 in Zombies was in the map Der Riese.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
     "question": "Pneumonoultramicroscopicsilicovolcanoconiosis is a synonym for the disease known as silicosis.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "Haggis is traditionally ate on Burns Night.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                       "question": "Sound can travel through a vacuum.", "correct_answer": "False",
                                       "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "Dave Grohl recorded the Foo Fighters debut, Foo Fighters, by himself.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Sports", "type": "boolean", "difficulty": "medium",
     "question": "During Wimbledon, spectators in the grounds can buy the tennis balls that have been used in matches.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Cartoon & Animations", "type": "boolean", "difficulty": "medium",
     "question": "Snagglepuss was part of the Yogi Yahooies in the 1977 show Scoobys All-Star Laff-a-Lympics.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "A Facebook campaign placed Rage Against The Machines Killing in the Name Of as the UK Christmas Number 1 in 2009.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
     "question": "The most frequent subconscious activity repeated by the human body is blinking.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "Metallica collaborated with Rowan Atkinsons Mr Bean on a 1992 comic relief single.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo. is a grammatically correct sentence.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "During pre-production of Super Mario Bros., Mario originally was meant to shoot bullets.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "A Boolean value of 0 represents which of these words?", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "medium",
     "question": "In Full Metal Panic!, Whispered are those who are capable of creating Black Technology.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
     "question": "The snowmobile was invented by Canadian Joseph-Armand Bombardier in 1937.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                       "question": "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "In the Resident Evil series, Leon S. Kennedy is a member of STARS.", "correct_answer": "False",
     "incorrect_answers": ["True"]}
]
